TASK 1


**The recomendation engine challenge** :

Because Python is an interpreted language, each loop iteration adds overhead, making the use of Python loops inefficient. Large vectors and matrices—often thousands at once—are involved in similarity computation.
Loops do not uutilize low level optimized libraries. For real-time systems like recommendation engines, execution becomes sluggish and inappropriate. By executing operations in compiled C code, NumPy circumvents this and significantly speeds up computations.

In [ ]:
#dot product and cosine similarity using using NumPy without using loops
import numpy as np
user = np.array([10, 20, 30])
product = np.array([40, 50, 60])

# Dot Product
dot_product = np.dot(user, product)
print("Dot Product:", dot_product)

# Cosine Similarity
cosine_similarity = dot_product / (np.linalg.norm(user) * np.linalg.norm(product))
print("Cosine Similarity:", cosine_similarity)

Dot Product: 3200
Cosine Similarity: 0.9746318461970763


In [ ]:
#pairwise distance computation between multiple users
import numpy as np
users = np.array([
    [1, 0, 2],
    [2, 1, 3],
    [0, 2, 1],
    [1, 1, 1]
])
# Dot product matrix (pairwise)
dot_matrix = users @ users.T
print("Dot Product Matrix:\n", dot_matrix)

# Norms of each user vector
norms = np.linalg.norm(users, axis=1)

# Pairwise cosine similarity
cosine_matrix = dot_matrix / (norms[:, None] * norms[None, :])
print("\nCosine Similarity Matrix:\n", cosine_matrix)

Dot Product Matrix:
 [[ 5  8  2  3]
 [ 8 14  5  6]
 [ 2  5  5  3]
 [ 3  6  3  3]]

Cosine Similarity Matrix:
 [[1.         0.95618289 0.4        0.77459667]
 [0.95618289 1.         0.5976143  0.9258201 ]
 [0.4        0.5976143  1.         0.77459667]
 [0.77459667 0.9258201  0.77459667 1.        ]]


**Vectorization improves performance and readability**:

Vectorization improves performance because
Operations run in optimized C-level code
Eliminates Python loop overhead
Enables parallel computation internally
It improves readability because:
Code is shorter and cleaner
Mathematical intent is clearer
Less chance of logical errors
Example Comparison
Loop-based: many lines, slow
NumPy-based: few lines, fast, readable