In [1]:
import numpy as np

# 2.3.1 Dot Product
print("\n2.3.1 Dot Product")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print(f"Vector a: {a}")
print(f"Vector b: {b}")
print(f"Dot product: {dot_product}")

# 2.3.2 Cosine Similarity
print("\n2.3.2 Cosine Similarity")
def cosine_similarity(x, y):
    return np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))

cos_sim = cosine_similarity(a, b)
print(f"Cosine similarity between a and b: {cos_sim}")

# Demonstrating with multiple users/products
user_vectors = np.array([
    [1, 0, 1, 0, 1],  # User 1 preferences
    [0, 1, 0, 1, 0],  # User 2 preferences
    [1, 1, 0, 0, 1]   # User 3 preferences
])
product_vectors = np.array([
    [1, 0, 0, 0, 1],  # Product A features
    [0, 1, 1, 1, 0],  # Product B features
    [1, 1, 1, 0, 0]   # Product C features
])

print("\nCosine Similarity between multiple user and product vectors:")
# Calculate all pairwise cosine similarities between users and products
# This can be done efficiently using matrix multiplication and broadcasting for norms

# Normalize user and product vectors
user_norms = np.linalg.norm(user_vectors, axis=1, keepdims=True)
product_norms = np.linalg.norm(product_vectors, axis=1, keepdims=True)

normalized_user_vectors = user_vectors / user_norms
normalized_product_vectors = product_vectors / product_norms

# Pairwise cosine similarity matrix (dot product of normalized vectors)
pairwise_cos_sim_matrix = np.dot(normalized_user_vectors, normalized_product_vectors.T)
print("Pairwise Cosine Similarity (Users x Products):")
print(pairwise_cos_sim_matrix)

# 2.3.3 Pairwise Distance Matrix (for users)
print("\n2.3.3 Pairwise Distance Matrix (between users)")
# Using the user_vectors for pairwise distance
X = user_vectors

pairwise_dist = np.sqrt(
    np.sum((X[:, None, :] - X[None, :, :])**2, axis=-1)
)
print("Pairwise Euclidean Distance (Users x Users):")
print(pairwise_dist)



2.3.1 Dot Product
Vector a: [1 2 3]
Vector b: [4 5 6]
Dot product: 32

2.3.2 Cosine Similarity
Cosine similarity between a and b: 0.9746318461970762

Cosine Similarity between multiple user and product vectors:
Pairwise Cosine Similarity (Users x Products):
[[0.81649658 0.33333333 0.66666667]
 [0.         0.81649658 0.40824829]
 [0.81649658 0.33333333 0.66666667]]

2.3.3 Pairwise Distance Matrix (between users)
Pairwise Euclidean Distance (Users x Users):
[[0.         2.23606798 1.41421356]
 [2.23606798 0.         1.73205081]
 [1.41421356 1.73205081 0.        ]]
